/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error": "#690005",
        "on-secondary-fixed-variant": "#005236",
        "outline": "#ab8982",
        "surface-container-lowest": "#0a0e18",
        "on-secondary": "#003824",
        "primary-container": "var(--color-primary-container, #ff5733)",
        "inverse-surface": "#dfe2f1",
        "surface-container-highest": "#313540",
        "on-tertiary-fixed": "#07006c",
        "on-secondary-fixed": "#002113",
        "secondary": "var(--color-secondary, #4edea3)",
        "secondary-fixed": "#6ffbbe",
        "inverse-primary": "#b72301",
        "on-primary-container": "#580c00",
        "surface-variant": "#313540",
        "on-secondary-container": "#00311f",
        "on-surface": "#dfe2f1",
        "error-container": "#93000a",
        "surface": "#0f131d",
        "on-tertiary-container": "#0d0097",
        "primary-fixed-dim": "#ffb4a4",
        "tertiary-fixed": "#e1e0ff",
        "on-background": "#dfe2f1",
        "on-primary": "#630e00",
        "inverse-on-surface": "#2c303b",
        "primary-fixed": "#ffdad3",
        "on-primary-fixed-variant": "#8c1800",
        "outline-variant": "#5b403a",
        "tertiary-fixed-dim": "#c0c1ff",
        "surface-container-high": "#262a35",
        "error": "#ffb4ab",
        "surface-container": "#1c1f2a",
        "on-primary-fixed": "#3d0600",
        "on-surface-variant": "#e4beb6",
        "on-error-container": "#ffdad6",
        "surface-tint": "#ffb4a4",
        "tertiary-container": "#8084ff",
        "background": "#0f131d",
        "secondary-fixed-dim": "var(--color-secondary, #4edea3)",
        "tertiary": "#c0c1ff",
        "on-tertiary": "#1000a9",
        "primary": "var(--color-primary, #ffb4a4)",
        "surface-container-low": "#171b26",
        "on-tertiary-fixed-variant": "#2f2ebe",
        "surface-bright": "#353944",
        "surface-dim": "#0f131d",
        "secondary-container": "var(--color-secondary-container, #00a572)",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        "space-sm": "0.5rem",
        "margin": "1rem",
        "space-xl": "2.5rem",
        "margin-desktop": "3rem",
        "space-md": "1rem",
        "space-xs": "0.25rem",
        "space-lg": "1.5rem",
        "gutter-desktop": "1.5rem",
        "gutter": "1rem",
      },
      fontFamily: {
        "headline-xl": ["Space Grotesk", "sans-serif"],
        "headline-sm": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Space Grotesk", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "currency-display": ["Space Grotesk", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl-mobile": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["44px", { lineHeight: "52px", fontWeight: "700" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "38px", fontWeight: "700" }],
        "headline-lg-mobile": ["26px", { lineHeight: "32px", fontWeight: "700" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "currency-display": ["28px", { lineHeight: "32px", fontWeight: "700" }],
        "label-sm": ["10px", { lineHeight: "12px", fontWeight: "700" }],
        "label-lg": ["15px", { lineHeight: "20px", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "headline-xl-mobile": ["34px", { lineHeight: "40px", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["22px", { lineHeight: "28px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}
