export const WEST_AFRICAN_COUNTRIES = [
  {
    code: "BF",
    name: "Burkina Faso",
    flag: "🇧🇫",
    dial: "+226",
    cities: [
      "Ouagadougou",
      "Bobo-Dioulasso",
      "Koudougou",
      "Ouahigouya",
      "Banfora",
      "Fada N'Gourma",
      "Kaya",
      "Dédougou",
      "Autre",
    ],
  },
  {
    code: "CI",
    name: "Côte d'Ivoire",
    flag: "🇨🇮",
    dial: "+225",
    cities: [
      "Abidjan",
      "Bouaké",
      "Yamoussoukro",
      "San Pedro",
      "Korhogo",
      "Daloa",
      "Autre",
    ],
  },
  {
    code: "ML",
    name: "Mali",
    flag: "🇲🇱",
    dial: "+223",
    cities: [
      "Bamako",
      "Sikasso",
      "Ségou",
      "Mopti",
      "Kayes",
      "Autre",
    ],
  },
  {
    code: "TG",
    name: "Togo",
    flag: "🇹🇬",
    dial: "+228",
    cities: [
      "Lomé",
      "Kara",
      "Sokodé",
      "Kpalimé",
      "Autre",
    ],
  },
  {
    code: "BJ",
    name: "Bénin",
    flag: "🇧🇯",
    dial: "+229",
    cities: [
      "Cotonou",
      "Porto-Novo",
      "Parakou",
      "Abomey-Calavi",
      "Autre",
    ],
  },
  {
    code: "SN",
    name: "Sénégal",
    flag: "🇸🇳",
    dial: "+221",
    cities: [
      "Dakar",
      "Thiès",
      "Saint-Louis",
      "Touba",
      "Mbour",
      "Autre",
    ],
  },
  {
    code: "NE",
    name: "Niger",
    flag: "🇳🇪",
    dial: "+227",
    cities: [
      "Niamey",
      "Zinder",
      "Maradi",
      "Tahoua",
      "Autre",
    ],
  },
  {
    code: "GN",
    name: "Guinée",
    flag: "🇬🇳",
    dial: "+224",
    cities: [
      "Conakry",
      "Kankan",
      "Kindia",
      "Nzérékoré",
      "Autre",
    ],
  },
  {
    code: "OTHER",
    name: "Autre Pays",
    flag: "🌍",
    dial: "+",
    cities: ["Autre"],
  },
];
